---
title: "Cowplot Transition into Sleep"
format: html
editor: visual
jupyter: python3
---

## Configuration

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'G:/My Drive/Residency/Research/Lab - Damisah/Project - Sleep')
```

```{r}
library(tidyverse)
library(cowplot)
```

## Parameters

```{r}
spectro <- readRDS('Cache/Subject01/S01_spectro_t5760.RDS')
zspike <- readRDS('Cache/Subject01/S01_zspike_t5760.RDS')
swa_1 <- readRDS('Cache/Subject01/S01_swa_t5760_part1.RDS')
spike_1 <- readRDS('Cache/Subject01/S01_spike_raster_t5760_part1.RDS')
swa_2 <- readRDS('Cache/Subject01/S01_swa_t5760_part2.RDS')
spike_2 <- readRDS('Cache/Subject01/S01_spike_raster_t5760_part2.RDS')

#S01-1: 1920 +/- 340 (zoom 1700, 2140 +/- 15)
#S01-3: 4140 +/- 480 (zoom 3840, 4440 +/- 15)

#S01-Experiment: 5760 +/- 340 (zoom 5540, 5980 +/- 15), y_limits = c(-0.75, 0.75)
```

```{r}
output_path_top <- 'Results/S01_transition_t5760_top.svg'
output_path_top_px <- 'Results/S01_transition_t5760_top.png'
output_path_bot <- 'Results/S01_transition_t5760_bottom.svg'
output_path_bot_px <- 'Results/S01_transition_t5760_bottom.png'
```

## Plotting

```{r}
spectro <- spectro + theme(legend.position = 'none', 
                           plot.margin = unit(c(1, 0, 0, 0), 'cm'))
zspike <- zspike + theme(legend.position = 'none', 
                         plot.margin = unit(c(0, 0, 1, 0), 'cm'))
swa_1 <- swa_1 + theme(legend.position = 'none', 
                       plot.margin = unit(c(1, 0, 0, 0), 'cm'))
spike_1 <- spike_1 + theme(legend.position = 'none', 
                           plot.margin = unit(c(0, 0, 1, 0), 'cm'))
swa_2 <- swa_2 + theme(legend.position = 'none', 
                       plot.margin = unit(c(1, 0, 0, 0), 'cm'))
spike_2 <- spike_2 + theme(legend.position = 'none', 
                           plot.margin = unit(c(0, 0, 1, 0), 'cm'))
```

```{r}
# Top Plot
plot_grid(spectro, zspike, 
          ncol = 1, align = 'v', axis = 'lr',
          rel_heights = c(1, 1))

ggsave(file = output_path_top, width = 10, height = 3.3, 
       dpi = 300, limitsize = FALSE)

ggsave(file = output_path_top_px, 
       width = 2600, height = 780, 
       units = 'px', limitsize = FALSE)
```

```{r}
# Bottom Plot
plot_grid(swa_1, spike_1, swa_2, spike_2, 
          ncol = 1, align = 'v',  axis = 'lr',
          rel_heights = c(1, 1, 1, 1))

ggsave(file = output_path_bot, width = 5, height = 5, 
       dpi = 300, limitsize = FALSE)

ggsave(file = output_path_bot_px, 
       width = 1300, height = 2000, 
       units = 'px', limitsize = FALSE)

```
