---
title: "Cowplot Transition out of Sleep"
format: html
editor: visual
jupyter: python3
---

## Configuration

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'G:/My Drive/Residency/Research/Lab - Damisah/Project - Sleep')
```

```{r}
library(tidyverse)
library(cowplot)
```

## Parameters

```{r}
spectro <- readRDS('Cache/Subject01/S01_spectro_t5715.RDS')
zspike <- readRDS('Cache/Subject01/S01_zspike_t5715.RDS')
swa <- readRDS('Cache/Subject01/S01_swa_t5715.RDS')
spike <- readRDS('Cache/Subject01/S01_spike_raster_t5715.RDS')

#S01-2: 3680 +/- 480 (zoom +/- 60)
#S01-4: 5715 +/- 180 (zoom +/- 30)
```

```{r}
output_path <- 'Results/S01_transition_t5715.svg'
output_path_pixel <- 'Results/S01_transition_t5715.png'
```

## Plotting

```{r}
spectro <- spectro + theme(legend.position = 'none', 
                           plot.margin = unit(c(1, 0, 0, 0), 'cm'))
zspike <- zspike + theme(legend.position = 'none', 
                         plot.margin = unit(c(0, 0, 1, 0), 'cm'))
swa <- swa + theme(legend.position = 'none', 
                   plot.margin = unit(c(1, 0, 0, 0), 'cm'))
spike <- spike + theme(legend.position = 'none', 
                       plot.margin = unit(c(0, 0, 1, 0), 'cm'))
```

```{r}
plot_grid(spectro, zspike, swa, spike, 
          ncol = 1, align = 'v', axis = 'lr',
          rel_heights = c(1, 1, 1, 1))

ggsave(file = output_path, width = 10, height = 7, 
       dpi = 300, limitsize = FALSE)

ggsave(file = output_path_pixel, 
       width = 2600, height = 1820, 
       units = 'px', limitsize = FALSE)
```
